# Generated by Django 3.0.7 on 2020-06-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='sorturl',
            field=models.CharField(max_length=200),
        ),
    ]
