# Generated by Django 3.0.7 on 2020-06-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0003_auto_20200618_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='counting',
            field=models.IntegerField(default=0),
        ),
    ]
